// Code generated by "enumer -type=TransactionType"; DO NOT EDIT.

package service

import (
	"fmt"
	"strings"
)

const _TransactionTypeName = "ExpenseTransfer"

var _TransactionTypeIndex = [...]uint8{0, 7, 15}

const _TransactionTypeLowerName = "expensetransfer"

func (i TransactionType) String() string {
	if i < 0 || i >= TransactionType(len(_TransactionTypeIndex)-1) {
		return fmt.Sprintf("TransactionType(%d)", i)
	}
	return _TransactionTypeName[_TransactionTypeIndex[i]:_TransactionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TransactionTypeNoOp() {
	var x [1]struct{}
	_ = x[Expense-(0)]
	_ = x[Transfer-(1)]
}

var _TransactionTypeValues = []TransactionType{Expense, Transfer}

var _TransactionTypeNameToValueMap = map[string]TransactionType{
	_TransactionTypeName[0:7]:       Expense,
	_TransactionTypeLowerName[0:7]:  Expense,
	_TransactionTypeName[7:15]:      Transfer,
	_TransactionTypeLowerName[7:15]: Transfer,
}

var _TransactionTypeNames = []string{
	_TransactionTypeName[0:7],
	_TransactionTypeName[7:15],
}

// TransactionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TransactionTypeString(s string) (TransactionType, error) {
	if val, ok := _TransactionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TransactionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TransactionType values", s)
}

// TransactionTypeValues returns all values of the enum
func TransactionTypeValues() []TransactionType {
	return _TransactionTypeValues
}

// TransactionTypeStrings returns a slice of all String values of the enum
func TransactionTypeStrings() []string {
	strs := make([]string, len(_TransactionTypeNames))
	copy(strs, _TransactionTypeNames)
	return strs
}

// IsATransactionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TransactionType) IsATransactionType() bool {
	for _, v := range _TransactionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
